{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "b1e5164e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "d62507a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import roc_auc_score\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from catboost import CatBoostClassifier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "2258ebf3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: imbalanced-learn in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (0.14.1)\n",
      "Requirement already satisfied: numpy<3,>=1.25.2 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from imbalanced-learn) (2.2.6)\n",
      "Requirement already satisfied: scipy<2,>=1.11.4 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from imbalanced-learn) (1.15.2)\n",
      "Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from imbalanced-learn) (1.7.2)\n",
      "Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from imbalanced-learn) (0.1.5)\n",
      "Requirement already satisfied: joblib<2,>=1.2.0 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from imbalanced-learn) (1.5.3)\n",
      "Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from imbalanced-learn) (3.6.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install imbalanced-learn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "a0822bec",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import StratifiedKFold, ParameterGrid\n",
    "from sklearn.metrics import (\n",
    "    average_precision_score, roc_auc_score,\n",
    "    fbeta_score, f1_score, accuracy_score\n",
    ")\n",
    "from sklearn.base import clone"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "38afb152",
   "metadata": {},
   "outputs": [],
   "source": [
    "test=pd.read_csv(\"C:/Users/Administrator/Desktop/채원이/test_data_fin.csv\", encoding=\"utf-8\")\n",
    "train=pd.read_csv(\"C:/Users/Administrator/Desktop/채원이/train_data_fin.csv\",  encoding=\"utf-8\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "6e1d4e2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#dummy함수 정의\n",
    "import pandas as pd\n",
    "\n",
    "def preprocess_train_test(\n",
    "    train: pd.DataFrame,\n",
    "    test: pd.DataFrame,\n",
    "    dummy_cols=(\"학년\", \"전임교원_확보율\", \"입학세부구분\"),\n",
    "    drop_cols=(\"혁신수업\", \"연구재단등재지\", \"Unnamed: 0\",\"계열\"),\n",
    "    ):\n",
    "    train = train.copy()\n",
    "    test = test.copy()\n",
    "\n",
    "    # 제외 변수 drop (train/test 둘 다에 없을 수도 있으니 errors=\"ignore\")\n",
    "    train = train.drop(columns=list(drop_cols), errors=\"ignore\")\n",
    "    test  = test.drop(columns=list(drop_cols), errors=\"ignore\")\n",
    "\n",
    "    # 더미 처리 대상 중 실제로 존재하는 컬럼만\n",
    "    dummy_cols = [c for c in dummy_cols if (c in train.columns or c in test.columns)]\n",
    "\n",
    "    # train+test를 합쳐서 한 번에 더미 만들고 다시 분리 (컬럼 불일치 방지)\n",
    "    n_train = len(train)\n",
    "    both = pd.concat([train, test], axis=0, ignore_index=True)\n",
    "\n",
    "    # 더미 처리, 범주형 -> 숫자\n",
    "    both = pd.get_dummies(both, columns=dummy_cols, drop_first=False)\n",
    "\n",
    "    X_train = both.iloc[:n_train, :].reset_index(drop=True)\n",
    "    X_test  = both.iloc[n_train:, :].reset_index(drop=True)\n",
    "\n",
    "    # (선택) 혹시 남아있는 object가 있으면 확인\n",
    "    # print(X_train.dtypes[X_train.dtypes == \"object\"])\n",
    "\n",
    "    return X_train, X_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "7040307c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import StratifiedKFold, ParameterGrid\n",
    "from sklearn.metrics import (\n",
    "    average_precision_score, roc_auc_score,\n",
    "    fbeta_score, f1_score, accuracy_score\n",
    ")\n",
    "from sklearn.base import clone\n",
    "\n",
    "BETA = 2.0\n",
    "N_SPLITS = 5\n",
    "RANDOM_STATE = 42\n",
    "\n",
    "# 타깃 변수명\n",
    "target_col = \"학적상태\"\n",
    "\n",
    "# 1) y 분리\n",
    "y_train_before = train[target_col].copy()\n",
    "y_test  = test[target_col].copy()\n",
    "\n",
    "# 2) X 분리\n",
    "X_train_raw = train.drop(columns=[target_col])\n",
    "X_test_raw  = test.drop(columns=[target_col])\n",
    "\n",
    "# 3) X 전처리\n",
    "X_train_before, X_test = preprocess_train_test(\n",
    "    X_train_raw,\n",
    "    X_test_raw,\n",
    "    dummy_cols=(\"학년\", \"전임교원_확보율\", \"입학세부구분\"),\n",
    "    drop_cols=(\"혁신수업\", \"연구재단등재지\", \"Unnamed: 0\",\"계열\"),\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "2411b311",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Before SMOTE:\n",
      "학적상태\n",
      "0    13964\n",
      "1      284\n",
      "Name: count, dtype: int64\n",
      "\n",
      "After SMOTE:\n",
      "학적상태\n",
      "0    13964\n",
      "1    13964\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "from imblearn.over_sampling import SMOTE\n",
    "\n",
    "# SMOTE 객체 생성\n",
    "smote = SMOTE(random_state=RANDOM_STATE)\n",
    "\n",
    "# SMOTE 적용 (train 데이터에만)\n",
    "X_train, y_train = smote.fit_resample(X_train_before, y_train_before)\n",
    "\n",
    "# 확인\n",
    "print(\"Before SMOTE:\")\n",
    "print(y_train_before.value_counts())\n",
    "print(\"\\nAfter SMOTE:\")\n",
    "print(y_train.value_counts())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "88fcc947",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "일반휴학학기수  평점평균      취업률  평균취득학점이상  학년_1  학년_2   학년_3   학년_4   전임교원_확보율_-1  전임교원_확보율_0  전임교원_확보율_1  입학세부구분_0  입학세부구분_1  입학세부구분_2\n",
      "0        0.000000  49   0         True  False  False  False  True         False       False       False     True      True        68\n",
      "                   53   0         True  False  False  False  True         False       False       False     True      False       58\n",
      "                   47   0         True  False  False  False  True         False       False       False     True      False       45\n",
      "                   40   0         True  False  False  False  True         False       True        True      True      False       39\n",
      "                   63   0         True  False  False  False  True         False       False       False     True      True        38\n",
      "                                                                                                                                  ..\n",
      "                   42   0         True  False  False  False  False        False       True        False     False     True         1\n",
      "         0.060000  48   0         True  False  False  False  True         False       False       False     True      False        1\n",
      "         0.060364  44   0         True  False  False  False  True         True        False       False     True      False        1\n",
      "         0.062501  27   0         True  False  False  False  False        False       True        False     True      True         1\n",
      "         0.000000  37   0         True  False  False  False  True         False       False       False     True      False        1\n",
      "Name: count, Length: 26335, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(X_train.value_counts())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "041880fe",
   "metadata": {},
   "source": [
    "# Catboost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "feb9af33",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: catboost in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (1.2.8)\n",
      "Requirement already satisfied: graphviz in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (0.21)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (3.10.8)\n",
      "Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (2.2.6)\n",
      "Requirement already satisfied: pandas>=0.24 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (2.3.3)\n",
      "Requirement already satisfied: scipy in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (1.15.2)\n",
      "Requirement already satisfied: plotly in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (6.5.0)\n",
      "Requirement already satisfied: six in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from catboost) (1.17.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from pandas>=0.24->catboost) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from pandas>=0.24->catboost) (2025.3)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (1.3.1)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (4.61.1)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (1.4.9)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (25.0)\n",
      "Requirement already satisfied: pillow>=8 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (12.0.0)\n",
      "Requirement already satisfied: pyparsing>=3 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from matplotlib->catboost) (3.3.1)\n",
      "Requirement already satisfied: narwhals>=1.15.1 in c:\\users\\administrator\\.conda\\envs\\shap_env\\lib\\site-packages (from plotly->catboost) (2.15.0)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!\"{sys.executable}\" -m pip install catboost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "69316409",
   "metadata": {},
   "outputs": [],
   "source": [
    "from catboost import CatBoostClassifier\n",
    "\n",
    "def fit_catboost_predict_proba(X_tr, y_tr, X_va, y_va, params):\n",
    "    model = CatBoostClassifier(\n",
    "        **params,\n",
    "        loss_function=\"Logloss\",\n",
    "        eval_metric=\"AUC\",\n",
    "        random_seed=RANDOM_STATE,\n",
    "        verbose=0,\n",
    "        thread_count=-1\n",
    "    )\n",
    "\n",
    "    model.fit(X_tr, y_tr, eval_set=(X_va, y_va))\n",
    "    proba = model.predict_proba(X_va)[:, 1]\n",
    "    return model, proba\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5ba0eafa",
   "metadata": {},
   "source": [
    "# SVM"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "d2693402",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "score min / mean / max: -3.1327198022926446 -1.464530246697058 1.387899269035489\n",
      "positives predicted (score>=0): 416 / 6106\n",
      "true positive rate: 0.020962987225679658\n"
     ]
    }
   ],
   "source": [
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.svm import SVC\n",
    "\n",
    "def make_svm_model(X_example, random_state=42):\n",
    "    # 더미화가 끝났으니 전체 컬럼을 numeric으로 보고 스케일링만\n",
    "    num_cols = X_example.columns.tolist()\n",
    "\n",
    "    preprocess = ColumnTransformer(\n",
    "        transformers=[\n",
    "            (\"num\", StandardScaler(), num_cols),\n",
    "        ],\n",
    "        remainder=\"drop\"\n",
    "    )\n",
    "\n",
    "    return Pipeline([\n",
    "        (\"prep\", preprocess),\n",
    "        (\"clf\", SVC(\n",
    "            kernel=\"rbf\",\n",
    "            C=1.0,\n",
    "            gamma=\"scale\",\n",
    "            probability=False,\n",
    "            random_state=random_state\n",
    "        ))\n",
    "    ])\n",
    "\n",
    "m = make_svm_model(X_train, random_state=RANDOM_STATE)\n",
    "m.fit(X_train, y_train)\n",
    "\n",
    "scores = m.decision_function(X_test)\n",
    "\n",
    "print(\"score min / mean / max:\", scores.min(), scores.mean(), scores.max())\n",
    "print(\"positives predicted (score>=0):\", (scores >= 0).sum(), \"/\", len(scores))\n",
    "print(\"true positive rate:\", y_test.mean())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2b3656b4",
   "metadata": {},
   "source": [
    "# RF"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "66538d78",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "\n",
    "def make_rf_model(X_example, random_state=RANDOM_STATE):\n",
    "    return Pipeline([\n",
    "        (\"clf\", RandomForestClassifier(\n",
    "            random_state=random_state,\n",
    "            n_jobs=-1\n",
    "        ))\n",
    "    ])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d3d07806",
   "metadata": {},
   "source": [
    "## gridsearch (train으로 -> valid)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "c69f6487",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import StratifiedKFold, ParameterGrid\n",
    "from sklearn.metrics import roc_auc_score, average_precision_score\n",
    "\n",
    "N_SPLITS = 5\n",
    "RANDOM_STATE = 42\n",
    "\n",
    "def custom_search_Xy(X, y, model_name, make_model_fn=None, param_grid=None):\n",
    "    if not param_grid:\n",
    "        raise ValueError(\"param_grid must be provided\")\n",
    "\n",
    "    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)\n",
    "    rows = []\n",
    "\n",
    "    for params_raw in ParameterGrid(param_grid):\n",
    "        fold_roc, fold_pr = [], []\n",
    "\n",
    "        for tr_idx, va_idx in skf.split(X, y):\n",
    "            X_tr, y_tr = X.iloc[tr_idx], y.iloc[tr_idx]\n",
    "            X_va, y_va = X.iloc[va_idx], y.iloc[va_idx]\n",
    "\n",
    "            if model_name == \"catboost\":\n",
    "                m, score = fit_catboost_predict_proba(X_tr, y_tr, X_va, y_va, params_raw)\n",
    "            else:\n",
    "                if make_model_fn is None:\n",
    "                    raise ValueError(\"make_model_fn must be provided for non-catboost models\")\n",
    "\n",
    "                m = make_model_fn(X_tr)\n",
    "\n",
    "                params_fit = dict(params_raw)      # fit용 복사본\n",
    "                params_fit.pop(\"class_weights\", None)\n",
    "                params_fit.pop(\"scale_pos_weight\", None)\n",
    "\n",
    "                m.set_params(**params_fit)\n",
    "                m.fit(X_tr, y_tr)\n",
    "\n",
    "                # SVM(probability=False)면 decision_function이 score\n",
    "                if hasattr(m, \"predict_proba\"):\n",
    "                    score = m.predict_proba(X_va)[:, 1]\n",
    "                else:\n",
    "                    score = m.decision_function(X_va)\n",
    "\n",
    "            fold_roc.append(roc_auc_score(y_va, score))\n",
    "            fold_pr.append(average_precision_score(y_va, score))\n",
    "\n",
    "        rows.append({\n",
    "            \"model\": model_name,\n",
    "            \"params\": dict(params_raw),  # ✅ 원본 그대로 저장\n",
    "            \"mean_ROC-AUC\": float(np.mean(fold_roc)),\n",
    "            \"mean_PR-AUC\": float(np.mean(fold_pr)),\n",
    "        })\n",
    "\n",
    "    res = (pd.DataFrame(rows)\n",
    "           .sort_values([\"mean_ROC-AUC\", \"mean_PR-AUC\"], ascending=False)\n",
    "           .reset_index(drop=True))\n",
    "    best = res.iloc[0].to_dict()\n",
    "    return best, res\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4c24cf67",
   "metadata": {},
   "source": [
    "### parameter 후보"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "843817f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "## full grid search, no balanced\n",
    "svm_grid = {\n",
    "    \"clf__kernel\": [\"rbf\"],\n",
    "    \"clf__C\": [0.25, 1.0, 4.0, 16.0, 64.0],\n",
    "    \"clf__gamma\": [\"scale\", 0.001, 0.01, 0.1, 1.0],\n",
    "}\n",
    "\n",
    "rf_grid = {\n",
    "    \"clf__n_estimators\": [300, 600],\n",
    "    \"clf__max_depth\": [None, 10, 20, 40],\n",
    "    \"clf__min_samples_leaf\": [1, 3, 5],\n",
    "    \"clf__max_features\": [\"sqrt\", 0.5],\n",
    "}\n",
    "\n",
    "cat_grid = {\n",
    "    \"iterations\": [800, 1200],\n",
    "    \"learning_rate\": [0.03, 0.05, 0.1],\n",
    "    \"depth\": [4, 6, 8],\n",
    "    \"l2_leaf_reg\": [1, 3, 10],\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e36dd87f",
   "metadata": {},
   "source": [
    "## no balanced best parameters search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "09b6deb4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "({'model': 'svm',\n",
       "  'params': {'clf__C': 64.0, 'clf__gamma': 'scale', 'clf__kernel': 'rbf'},\n",
       "  'mean_ROC-AUC': 0.9897116846991814,\n",
       "  'mean_PR-AUC': 0.9895124744696877},\n",
       " {'model': 'rf',\n",
       "  'params': {'clf__max_depth': 20,\n",
       "   'clf__max_features': 'sqrt',\n",
       "   'clf__min_samples_leaf': 1,\n",
       "   'clf__n_estimators': 600},\n",
       "  'mean_ROC-AUC': 0.9970042889922368,\n",
       "  'mean_PR-AUC': 0.996778901252584},\n",
       " {'model': 'catboost',\n",
       "  'params': {'depth': 8,\n",
       "   'iterations': 1200,\n",
       "   'l2_leaf_reg': 1,\n",
       "   'learning_rate': 0.1},\n",
       "  'mean_ROC-AUC': 0.997146500760296,\n",
       "  'mean_PR-AUC': 0.9971675006420181})"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "best_svm, res_svm = custom_search_Xy(\n",
    "    X_train, y_train,\n",
    "    model_name=\"svm\",\n",
    "    make_model_fn=make_svm_model,\n",
    "    param_grid=svm_grid\n",
    ")\n",
    "\n",
    "best_rf, res_rf = custom_search_Xy(\n",
    "    X_train, y_train,\n",
    "    model_name=\"rf\",\n",
    "    make_model_fn=make_rf_model,\n",
    "    param_grid=rf_grid\n",
    ")  \n",
    "\n",
    "best_cat, res_cat = custom_search_Xy(\n",
    "    X_train, y_train,\n",
    "    model_name=\"catboost\",\n",
    "    param_grid=cat_grid\n",
    ")\n",
    "\n",
    "best_svm, best_rf, best_cat\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "434c87ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "best_svm = {\n",
    "    \"model\": \"svm\",\n",
    "    \"params\": {\n",
    "        \"clf__C\": 64.0,\n",
    "        \"clf__gamma\": \"scale\",\n",
    "        \"clf__kernel\": \"rbf\",\n",
    "    },\n",
    "    \"mean_ROC-AUC\": 0.9897116846991814,\n",
    "    \"mean_PR-AUC\": 0.9895124744696877,\n",
    "}\n",
    "\n",
    "best_rf = {\n",
    "    \"model\": \"rf\",\n",
    "    \"params\": {\n",
    "        \"clf__max_depth\": 20,\n",
    "        \"clf__max_features\": \"sqrt\",\n",
    "        \"clf__min_samples_leaf\": 1,\n",
    "        \"clf__n_estimators\": 600,\n",
    "    },\n",
    "    \"mean_ROC-AUC\": 0.9970042889922368,\n",
    "    \"mean_PR-AUC\": 0.996778901252584,\n",
    "}\n",
    "\n",
    "best_cat = {\n",
    "    \"model\": \"catboost\",\n",
    "    \"params\": {\n",
    "        \"depth\": 8,\n",
    "        \"iterations\": 1200,\n",
    "        \"l2_leaf_reg\": 1,\n",
    "        \"learning_rate\": 0.1,\n",
    "    },\n",
    "    \"mean_ROC-AUC\": 0.997146500760296,\n",
    "    \"mean_PR-AUC\": 0.9971675006420181,\n",
    "}\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e94268d",
   "metadata": {},
   "source": [
    "## Best params 지표 (SMOTE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "08d632c3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>ROC-AUC</th>\n",
       "      <th>Recall</th>\n",
       "      <th>F1</th>\n",
       "      <th>Accuracy</th>\n",
       "      <th>Precision</th>\n",
       "      <th>Pred_Pos</th>\n",
       "      <th>Thr_used</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>catboost</td>\n",
       "      <td>0.873466</td>\n",
       "      <td>0.250000</td>\n",
       "      <td>0.212625</td>\n",
       "      <td>0.961186</td>\n",
       "      <td>0.184971</td>\n",
       "      <td>173</td>\n",
       "      <td>0.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>svm</td>\n",
       "      <td>0.815425</td>\n",
       "      <td>0.414062</td>\n",
       "      <td>0.210736</td>\n",
       "      <td>0.934982</td>\n",
       "      <td>0.141333</td>\n",
       "      <td>375</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>rf</td>\n",
       "      <td>0.882738</td>\n",
       "      <td>0.234375</td>\n",
       "      <td>0.189873</td>\n",
       "      <td>0.958074</td>\n",
       "      <td>0.159574</td>\n",
       "      <td>188</td>\n",
       "      <td>0.5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      model   ROC-AUC    Recall        F1  Accuracy  Precision  Pred_Pos  \\\n",
       "0  catboost  0.873466  0.250000  0.212625  0.961186   0.184971       173   \n",
       "1       svm  0.815425  0.414062  0.210736  0.934982   0.141333       375   \n",
       "2        rf  0.882738  0.234375  0.189873  0.958074   0.159574       188   \n",
       "\n",
       "   Thr_used  \n",
       "0       0.5  \n",
       "1       0.0  \n",
       "2       0.5  "
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.metrics import roc_auc_score, f1_score, recall_score, accuracy_score, precision_score\n",
    "\n",
    "def metrics_simple(y_true, score, thr):\n",
    "    pred = (score >= thr).astype(int)\n",
    "    return {\n",
    "        \"ROC-AUC\": roc_auc_score(y_true, score),\n",
    "        \"Recall\": recall_score(y_true, pred),\n",
    "        \"F1\": f1_score(y_true, pred),\n",
    "        \"Accuracy\": accuracy_score(y_true, pred),\n",
    "        \"Precision\": precision_score(y_true, pred, zero_division=0),\n",
    "        \"Pred_Pos\": int(pred.sum()),\n",
    "        \"Thr_used\": thr,\n",
    "    }\n",
    "\n",
    "target_col = \"학적상태\"\n",
    "y_test  = test[target_col].copy()\n",
    "\n",
    "def fit_final_and_eval(model_name, best):\n",
    "    if model_name == \"catboost\":\n",
    "        m = CatBoostClassifier(\n",
    "            **best[\"params\"],\n",
    "            loss_function=\"Logloss\",\n",
    "            eval_metric=\"AUC\",\n",
    "            random_seed=RANDOM_STATE,\n",
    "            verbose=0,\n",
    "            thread_count=-1\n",
    "        )\n",
    "        m.fit(X_train, y_train)\n",
    "        score = m.predict_proba(X_test)[:, 1]\n",
    "        thr = 0.5\n",
    "\n",
    "    elif model_name == \"svm\":\n",
    "        m = make_svm_model(X_train)\n",
    "        m.set_params(**best[\"params\"])\n",
    "        m.fit(X_train, y_train)\n",
    "        score = m.decision_function(X_test)\n",
    "        thr = 0.0\n",
    "\n",
    "    elif model_name == \"rf\":\n",
    "        m = make_rf_model(X_train)     # ✅ 수정 포인트\n",
    "        m.set_params(**best[\"params\"])\n",
    "        m.fit(X_train, y_train)\n",
    "        score = m.predict_proba(X_test)[:, 1]\n",
    "        thr = 0.5\n",
    "\n",
    "    mets = metrics_simple(y_test, score, thr)\n",
    "    return {\"model\": model_name, **mets}\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "7c6b14e5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>ROC-AUC</th>\n",
       "      <th>Recall</th>\n",
       "      <th>F1</th>\n",
       "      <th>Accuracy</th>\n",
       "      <th>Precision</th>\n",
       "      <th>Pred_Pos</th>\n",
       "      <th>Thr_used</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>catboost</td>\n",
       "      <td>0.8735</td>\n",
       "      <td>0.2500</td>\n",
       "      <td>0.2126</td>\n",
       "      <td>0.9612</td>\n",
       "      <td>0.1850</td>\n",
       "      <td>173</td>\n",
       "      <td>0.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>svm</td>\n",
       "      <td>0.8154</td>\n",
       "      <td>0.4141</td>\n",
       "      <td>0.2107</td>\n",
       "      <td>0.9350</td>\n",
       "      <td>0.1413</td>\n",
       "      <td>375</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>rf</td>\n",
       "      <td>0.8827</td>\n",
       "      <td>0.2344</td>\n",
       "      <td>0.1899</td>\n",
       "      <td>0.9581</td>\n",
       "      <td>0.1596</td>\n",
       "      <td>188</td>\n",
       "      <td>0.5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      model  ROC-AUC  Recall      F1  Accuracy  Precision  Pred_Pos  Thr_used\n",
       "0  catboost   0.8735  0.2500  0.2126    0.9612     0.1850       173       0.5\n",
       "1       svm   0.8154  0.4141  0.2107    0.9350     0.1413       375       0.0\n",
       "2        rf   0.8827  0.2344  0.1899    0.9581     0.1596       188       0.5"
      ]
     },
     "execution_count": 47,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "summary = (\n",
    "    pd.DataFrame([\n",
    "        fit_final_and_eval(\"svm\", best_svm),\n",
    "        fit_final_and_eval(\"rf\",  best_rf),\n",
    "        fit_final_and_eval(\"catboost\", best_cat),\n",
    "    ])\n",
    "    .sort_values(by=\"F1\", ascending=False)\n",
    "    .reset_index(drop=True)\n",
    ")\n",
    "\n",
    "summary_rounded = summary.round(4)\n",
    "summary_rounded"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (shap_env)",
   "language": "python",
   "name": "shap_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
